package arch

import (
	"errors"
	"fmt"
	"sort"

	"github.com/ShaneDolphin/gorapide"
	"github.com/ShaneDolphin/gorapide/pattern"
)

var (
	ErrInvalidExceptionDeclaration = errors.New("invalid declarative Rapide exception declaration")
	ErrInvalidExceptionHandler     = errors.New("invalid declarative Rapide exception handler")
	ErrUnhandledRapideException    = errors.New("unhandled Rapide exception")
)

// ExceptionDeclaration is an event signature that may only be generated by a
// raise statement and selected by an active handler.
type ExceptionDeclaration struct {
	Declaration string
	Name        string
	Params      []ParamDecl
}

type canonicalExceptionDeclaration struct {
	Declaration string               `json:"declaration"`
	Name        string               `json:"name"`
	Params      []canonicalParamDecl `json:"params"`
}

func canonicalizeExceptionDeclarations(
	component *Component,
	declarations []ExceptionDeclaration,
) ([]canonicalExceptionDeclaration, error) {
	result := make([]canonicalExceptionDeclaration, 0, len(declarations))
	seen := make(map[string]bool, len(declarations))
	for _, declaration := range declarations {
		if declaration.Declaration == "" || declaration.Name == "" ||
			seen[declaration.Declaration] {
			return nil, fmt.Errorf("exception %q has an empty or duplicate declaration identity %q",
				declaration.Name, declaration.Declaration)
		}
		if component != nil && component.Interface != nil {
			for _, action := range component.Interface.Actions {
				if action.Name == declaration.Name {
					return nil, fmt.Errorf("exception %q conflicts with an action", declaration.Name)
				}
			}
			for _, function := range component.Interface.Functions {
				if function.Name == declaration.Name {
					return nil, fmt.Errorf("exception %q conflicts with a function", declaration.Name)
				}
			}
		}
		encoded := canonicalExceptionDeclaration{Declaration: declaration.Declaration, Name: declaration.Name}
		seenParams := make(map[string]bool, len(declaration.Params))
		for _, parameter := range declaration.Params {
			if parameter.Name == "" || parameter.Type == "" || parameter.Default != nil ||
				seenParams[parameter.Name] || !supportedPredefinedType(parameter.Type) {
				return nil, fmt.Errorf("exception %q has invalid predefined-scalar parameter %q:%q",
					declaration.Name, parameter.Name, parameter.Type)
			}
			if _, structural := parameter.StructuralRapideType(); structural {
				return nil, fmt.Errorf("exception %q parameter %q is structural", declaration.Name, parameter.Name)
			}
			seenParams[parameter.Name] = true
			encoded.Params = append(encoded.Params, canonicalParamDecl{Name: parameter.Name, Type: parameter.Type})
		}
		seen[declaration.Declaration] = true
		result = append(result, encoded)
	}
	sort.Slice(result, func(left, right int) bool { return result[left].Declaration < result[right].Declaration })
	return result, nil
}

// Exception declares one exception-event signature for a generated module.
func Exception(name string, params ...ParamDecl) ExceptionDeclaration {
	return ExceptionDeclaration{Name: name, Params: append([]ParamDecl(nil), params...)}
}

// DeclaredException creates an exception signature with an explicit lexical
// declaration identity. Separate module instances generated from the same
// declaration must use the same identity; same-spelling declarations in
// different scopes must use different identities.
func DeclaredException(declaration, name string, params ...ParamDecl) ExceptionDeclaration {
	return ExceptionDeclaration{
		Declaration: declaration, Name: name, Params: append([]ParamDecl(nil), params...),
	}
}

// AddExceptionDeclaration adds one lexically visible module exception. The
// deterministic-model pass validates names, types, and constituent conflicts.
func (component *Component) AddExceptionDeclaration(declaration ExceptionDeclaration) error {
	if component == nil {
		return fmt.Errorf("%w: component is nil", ErrInvalidExceptionDeclaration)
	}
	if declaration.Name == "" {
		return fmt.Errorf("%w: component %q exception has no name", ErrInvalidExceptionDeclaration, component.ID)
	}
	copy := ExceptionDeclaration{
		Declaration: declaration.Declaration,
		Name:        declaration.Name,
		Params:      append([]ParamDecl(nil), declaration.Params...),
	}
	component.mu.Lock()
	defer component.mu.Unlock()
	if copy.Declaration == "" {
		copy.Declaration = "component:" + component.ID + ":exception:" + copy.Name
	}
	for _, existing := range component.exceptions {
		if existing.Declaration == copy.Declaration {
			return fmt.Errorf("%w: component %q has duplicate exception declaration %q",
				ErrInvalidExceptionDeclaration, component.ID, copy.Declaration)
		}
	}
	component.exceptions = append(component.exceptions, copy)
	return nil
}

// SetModuleExceptionHandler installs the handler part of a generated module
// definition. Canonical-model construction validates its declarations,
// bindings, statement subset, and deterministic identity.
func (component *Component) SetModuleExceptionHandler(handler ExceptionHandler) error {
	if component == nil {
		return fmt.Errorf("%w: component is nil", ErrInvalidExceptionHandler)
	}
	if len(handler.Choices) == 0 && handler.Else == nil {
		return fmt.Errorf("%w: component %q module handler is empty", ErrInvalidExceptionHandler, component.ID)
	}
	copy := copyExceptionHandler(handler)
	component.mu.Lock()
	defer component.mu.Unlock()
	if component.moduleHandler != nil {
		return fmt.Errorf("%w: component %q already has a module handler", ErrInvalidExceptionHandler, component.ID)
	}
	component.moduleHandler = &copy
	return nil
}

type ExceptionHandlerBinding struct {
	Formal      string
	Placeholder string
	Type        string
}

type ExceptionHandlerChoice struct {
	Exception            string
	ExceptionDeclaration string
	Action               string
	Any                  bool
	Bindings             []ExceptionHandlerBinding
	Statements           []Statement
}

type ExceptionHandler struct {
	Choices []ExceptionHandlerChoice
	Else    []Statement
}

type canonicalExceptionHandlerBinding struct {
	Formal      string `json:"formal"`
	Placeholder string `json:"placeholder"`
	Type        string `json:"type"`
}

type canonicalExceptionHandlerChoice struct {
	Exception            string                             `json:"exception,omitempty"`
	ExceptionDeclaration string                             `json:"exception_declaration,omitempty"`
	Action               string                             `json:"action,omitempty"`
	Any                  bool                               `json:"any,omitempty"`
	Bindings             []canonicalExceptionHandlerBinding `json:"bindings"`
	Statements           []canonicalRuleStatement           `json:"statements"`
}

type canonicalExceptionHandler struct {
	Choices []canonicalExceptionHandlerChoice `json:"choices"`
	Else    []canonicalRuleStatement          `json:"else,omitempty"`
}

func HandleException(
	exception string,
	bindings []ExceptionHandlerBinding,
	statements ...Statement,
) ExceptionHandlerChoice {
	return ExceptionHandlerChoice{
		Exception:  exception,
		Bindings:   append([]ExceptionHandlerBinding(nil), bindings...),
		Statements: copyStatements(statements),
	}
}

// HandleDeclaredException selects one exact lexical exception declaration.
func HandleDeclaredException(
	declaration string,
	exception string,
	bindings []ExceptionHandlerBinding,
	statements ...Statement,
) ExceptionHandlerChoice {
	return ExceptionHandlerChoice{
		Exception: exception, ExceptionDeclaration: declaration,
		Bindings:   append([]ExceptionHandlerBinding(nil), bindings...),
		Statements: copyStatements(statements),
	}
}

// HandleInterrupt adds one visible action choice to a block handler. The
// immediate deterministic slice activates it only while the protected block is
// executing; module-level handlers reject action choices because they have no
// enclosing procedural block in the current kernel.
func HandleInterrupt(
	action string,
	bindings []ExceptionHandlerBinding,
	statements ...Statement,
) ExceptionHandlerChoice {
	return ExceptionHandlerChoice{
		Action:     action,
		Bindings:   append([]ExceptionHandlerBinding(nil), bindings...),
		Statements: copyStatements(statements),
	}
}

// HandleAnyEvent adds the predefined any pattern as a handler choice. The
// bounded deterministic slice requires it to be the handler's sole choice so
// one occurrence cannot overlap both a named choice and any.
func HandleAnyEvent(statements ...Statement) ExceptionHandlerChoice {
	return ExceptionHandlerChoice{Any: true, Statements: copyStatements(statements)}
}

func HandleExceptions(body []Statement, handler ExceptionHandler) Statement {
	return Statement{
		kind:        HandlerBlockStatementKind,
		handledBody: copyStatements(body),
		handler:     copyExceptionHandler(handler),
	}
}

// HandleDo applies a handler to a Rapide do statement. Unlike a handler on a
// function or module block, this construct is also a target for exit and next.
func HandleDo(body []Statement, handler ExceptionHandler) Statement {
	statement := HandleExceptions(body, handler)
	statement.doControl = true
	return statement
}

func copyExceptionHandler(handler ExceptionHandler) ExceptionHandler {
	result := ExceptionHandler{Else: copyStatements(handler.Else)}
	result.Choices = make([]ExceptionHandlerChoice, len(handler.Choices))
	for index, choice := range handler.Choices {
		result.Choices[index] = ExceptionHandlerChoice{
			Exception: choice.Exception, ExceptionDeclaration: choice.ExceptionDeclaration,
			Action: choice.Action, Any: choice.Any,
			Bindings:   append([]ExceptionHandlerBinding(nil), choice.Bindings...),
			Statements: copyStatements(choice.Statements),
		}
	}
	return result
}

func exceptionHandlerChoiceKey(choice ExceptionHandlerChoice) string {
	if choice.Any {
		return "any\x00"
	}
	if choice.Exception != "" {
		return "exception\x00" + choice.ExceptionDeclaration + "\x00" + choice.Exception
	}
	return "action\x00" + choice.Action
}

func canonicalExceptionHandlerChoiceKey(choice canonicalExceptionHandlerChoice) string {
	if choice.Any {
		return "any\x00"
	}
	if choice.Exception != "" {
		return "exception\x00" + choice.ExceptionDeclaration + "\x00" + choice.Exception
	}
	return "action\x00" + choice.Action
}

func handlerActionDeclaration(component *Component, name string) (ActionDecl, bool) {
	if component == nil || component.Interface == nil || name == "" {
		return ActionDecl{}, false
	}
	for _, action := range component.Interface.Actions {
		if action.Name == name {
			return action, true
		}
	}
	for _, service := range component.Interface.Services {
		for _, action := range service.Actions {
			if action.Name == name {
				return action, true
			}
		}
	}
	return ActionDecl{}, false
}

func statementTreeAllocatesModule(statement Statement) bool {
	for _, parameter := range statement.output.Parameters {
		if ruleValueAllocatesModule(parameter.Value) {
			return true
		}
	}
	groups := [][]Statement{
		statement.thenBranch, statement.elseBranch, statement.loopBody,
		statement.caseDefault, statement.handledBody, statement.handler.Else,
	}
	for _, alternative := range statement.caseAlts {
		groups = append(groups, alternative.body)
	}
	for _, choice := range statement.handler.Choices {
		groups = append(groups, choice.Statements)
	}
	for _, group := range groups {
		for _, child := range group {
			if statementTreeAllocatesModule(child) {
				return true
			}
		}
	}
	return false
}

func ruleValueAllocatesModule(value RuleValue) bool {
	if value.kind == RuleNewValue {
		return true
	}
	for _, operand := range value.operands {
		if ruleValueAllocatesModule(operand) {
			return true
		}
	}
	return false
}

func exceptionDeclaration(component *Component, declarationIdentity, name string) (ExceptionDeclaration, bool) {
	if component == nil {
		return ExceptionDeclaration{}, false
	}
	var result ExceptionDeclaration
	found := false
	for _, declaration := range component.exceptions {
		if declaration.Name != name {
			continue
		}
		if declarationIdentity != "" {
			if declaration.Declaration == declarationIdentity {
				return declaration, true
			}
			continue
		}
		if found {
			return ExceptionDeclaration{}, false
		}
		result, found = declaration, true
	}
	return result, found
}

func exceptionOutputShapeMatches(
	component *Component,
	declarationIdentity string,
	output RuleOutput,
	stateTypes, placeholderTypes map[string]string,
) bool {
	declaration, exists := exceptionDeclaration(component, declarationIdentity, output.Action)
	if !exists || len(declaration.Params) != len(output.Parameters) {
		return false
	}
	byName := make(map[string]ParamDecl, len(declaration.Params))
	for _, parameter := range declaration.Params {
		byName[parameter.Name] = parameter
	}
	for _, parameter := range output.Parameters {
		expected, exists := byName[parameter.Name]
		if !exists {
			return false
		}
		_, _, actualType, err := canonicalizeClosedRuleValue(
			"exception "+output.Action+" parameter "+parameter.Name,
			parameter.Value, stateTypes, placeholderTypes,
		)
		if err != nil || !ruleValueAssignableToPredefined(parameter.Value, actualType, expected.Type) {
			return false
		}
		if parameter.Value.kind == RuleLiteralValue && !valueMatchesPredefinedType(parameter.Value.literal, expected.Type) {
			return false
		}
	}
	return true
}

func canonicalizeExceptionHandlerBlock(
	component *Component,
	owner string,
	statement Statement,
	stateTypes, placeholderTypes map[string]string,
	functions map[string]*FunctionImplementation,
	functionReturnType *string,
	seenOutputs map[string]bool,
	path string,
	loopDepth int,
	doStack []string,
	allowProcessDoControl bool,
	allowTimingSuspension bool,
	allowReraise bool,
	allowInterrupt bool,
	allowProcessInterruptAllocation bool,
) (Statement, canonicalRuleStatement, error) {
	doName, err := canonicalDoName(statement.doName)
	if err != nil || (doName != "" && !statement.doControl) {
		return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
			"%w: %s handler block %s has invalid do name %q",
			ErrInvalidExceptionHandler, owner, path, statement.doName)
	}
	blockLoopDepth := loopDepth
	blockDoStack := doStack
	if statement.doControl {
		blockLoopDepth++
		blockDoStack = pushDoName(doStack, doName)
	}
	if len(statement.handledBody) == 0 || (len(statement.handler.Choices) == 0 && statement.handler.Else == nil) {
		return Statement{}, canonicalRuleStatement{}, fmt.Errorf("%w: %s handler block %s is empty",
			ErrInvalidExceptionHandler, owner, path)
	}
	hasInterruptChoice := false
	hasAnyChoice := false
	for _, choice := range statement.handler.Choices {
		hasInterruptChoice = hasInterruptChoice || choice.Action != "" || choice.Any
		hasAnyChoice = hasAnyChoice || choice.Any
	}
	if hasAnyChoice && (len(statement.handler.Choices) != 1 || statement.handler.Else != nil) {
		return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
			"%w: %s predefined any pattern must be the handler's sole choice",
			ErrInvalidExceptionHandler, owner)
	}
	if hasInterruptChoice && !allowProcessInterruptAllocation {
		for _, candidate := range statement.handledBody {
			if statementTreeAllocatesModule(candidate) {
				return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
					"%w: %s module allocation while a non-process interrupt handler is active requires owner-lifetime semantics",
					ErrInvalidExceptionHandler, owner)
			}
		}
	}
	normalizedBody, canonicalBody, err := canonicalizeRuleStatementList(
		component, owner+" handled block "+path, statement.handledBody,
		stateTypes, placeholderTypes, functions, functionReturnType, seenOutputs,
		path+"b/", blockLoopDepth, blockDoStack,
		allowProcessDoControl, allowTimingSuspension, allowReraise,
		allowProcessInterruptAllocation,
	)
	if err != nil {
		return Statement{}, canonicalRuleStatement{}, err
	}
	normalized := Statement{
		kind: HandlerBlockStatementKind, doControl: statement.doControl,
		doName: doName, handledBody: normalizedBody,
	}
	canonical := canonicalRuleStatement{
		Kind: HandlerBlockStatementKind, DoControl: statement.doControl,
		DoName: doName, Body: canonicalBody,
		Handler: &canonicalExceptionHandler{},
	}
	seenChoices := make(map[string]bool, len(statement.handler.Choices))
	for choiceIndex, choice := range statement.handler.Choices {
		choiceKind := "exception"
		choiceName := choice.Exception
		var parameters []ParamDecl
		if choice.Any && choice.Exception == "" && choice.Action == "" {
			choiceKind = "any"
			choiceName = "any"
			if !allowInterrupt {
				return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
					"%w: %s handler any pattern requires an enclosing active procedural block",
					ErrInvalidExceptionHandler, owner)
			}
			if len(choice.Bindings) != 0 {
				return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
					"%w: %s predefined any handler pattern cannot bind parameters",
					ErrInvalidExceptionHandler, owner)
			}
		} else if !choice.Any && choice.Exception != "" && choice.Action == "" {
			declaration, exists := exceptionDeclaration(
				component, choice.ExceptionDeclaration, choice.Exception,
			)
			if !exists {
				return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
					"%w: %s handler choice %d names missing exception declaration %q (%q)",
					ErrInvalidExceptionHandler, owner, choiceIndex,
					choice.ExceptionDeclaration, choice.Exception)
			}
			choice.ExceptionDeclaration = declaration.Declaration
			parameters = declaration.Params
		} else if !choice.Any && choice.Action != "" && choice.Exception == "" {
			choiceKind = "action"
			choiceName = choice.Action
			if !allowInterrupt {
				return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
					"%w: %s handler action %q requires an enclosing active procedural block",
					ErrInvalidExceptionHandler, owner, choice.Action)
			}
			declaration, exists := handlerActionDeclaration(component, choice.Action)
			if !exists {
				return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
					"%w: %s handler choice %d names missing action %q",
					ErrInvalidExceptionHandler, owner, choiceIndex, choice.Action)
			}
			parameters = declaration.Params
		} else {
			return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
				"%w: %s handler choice %d must name exactly one exception, action, or predefined any pattern",
				ErrInvalidExceptionHandler, owner, choiceIndex)
		}
		choiceKey := choiceKind + "\x00" + choice.ExceptionDeclaration + "\x00" + choiceName
		if seenChoices[choiceKey] {
			return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
				"%w: %s handler has duplicate %s choice %q",
				ErrInvalidExceptionHandler, owner, choiceKind, choiceName)
		}
		seenChoices[choiceKey] = true
		formals := make(map[string]ParamDecl, len(parameters))
		for _, formal := range parameters {
			formals[formal.Name] = formal
		}
		choicePlaceholderTypes := make(map[string]string, len(placeholderTypes)+len(choice.Bindings))
		for name, typeName := range placeholderTypes {
			choicePlaceholderTypes[name] = typeName
		}
		normalizedChoice := ExceptionHandlerChoice{
			Exception: choice.Exception, ExceptionDeclaration: choice.ExceptionDeclaration,
			Action: choice.Action, Any: choice.Any,
		}
		canonicalChoice := canonicalExceptionHandlerChoice{
			Exception: choice.Exception, ExceptionDeclaration: choice.ExceptionDeclaration,
			Action: choice.Action, Any: choice.Any,
		}
		seenFormals := make(map[string]bool, len(choice.Bindings))
		for _, binding := range choice.Bindings {
			formal, exists := formals[binding.Formal]
			if !exists || seenFormals[binding.Formal] || binding.Placeholder == "" ||
				binding.Type != formal.Type || choicePlaceholderTypes[binding.Placeholder] != "" {
				return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
					"%w: %s %s %q has invalid handler binding %q -> %q:%q",
					ErrInvalidExceptionHandler, owner, choiceKind, choiceName,
					binding.Formal, binding.Placeholder, binding.Type)
			}
			seenFormals[binding.Formal] = true
			choicePlaceholderTypes[binding.Placeholder] = binding.Type
			normalizedChoice.Bindings = append(normalizedChoice.Bindings, binding)
			canonicalChoice.Bindings = append(canonicalChoice.Bindings, canonicalExceptionHandlerBinding{
				Formal: binding.Formal, Placeholder: binding.Placeholder, Type: binding.Type,
			})
		}
		sort.Slice(normalizedChoice.Bindings, func(left, right int) bool {
			return normalizedChoice.Bindings[left].Formal < normalizedChoice.Bindings[right].Formal
		})
		sort.Slice(canonicalChoice.Bindings, func(left, right int) bool {
			return canonicalChoice.Bindings[left].Formal < canonicalChoice.Bindings[right].Formal
		})
		normalizedStatements, canonicalStatements, err := canonicalizeRuleStatementList(
			component, owner+" handler "+choiceName, choice.Statements,
			stateTypes, choicePlaceholderTypes, functions, functionReturnType, seenOutputs,
			fmt.Sprintf("%sh%d/", path, choiceIndex), blockLoopDepth, blockDoStack,
			allowProcessDoControl, allowTimingSuspension, choiceKind == "exception",
			allowProcessInterruptAllocation,
		)
		if err != nil {
			return Statement{}, canonicalRuleStatement{}, err
		}
		if len(normalizedStatements) == 0 {
			return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
				"%w: %s %s %q handler body is empty", ErrInvalidExceptionHandler, owner, choiceKind, choiceName)
		}
		normalizedChoice.Statements = normalizedStatements
		canonicalChoice.Statements = canonicalStatements
		normalized.handler.Choices = append(normalized.handler.Choices, normalizedChoice)
		canonical.Handler.Choices = append(canonical.Handler.Choices, canonicalChoice)
	}
	sort.Slice(normalized.handler.Choices, func(left, right int) bool {
		return exceptionHandlerChoiceKey(normalized.handler.Choices[left]) <
			exceptionHandlerChoiceKey(normalized.handler.Choices[right])
	})
	sort.Slice(canonical.Handler.Choices, func(left, right int) bool {
		return canonicalExceptionHandlerChoiceKey(canonical.Handler.Choices[left]) <
			canonicalExceptionHandlerChoiceKey(canonical.Handler.Choices[right])
	})
	if statement.handler.Else != nil {
		normalizedElse, canonicalElse, err := canonicalizeRuleStatementList(
			component, owner+" handler else", statement.handler.Else,
			stateTypes, placeholderTypes, functions, functionReturnType, seenOutputs,
			path+"he/", blockLoopDepth, blockDoStack,
			allowProcessDoControl, allowTimingSuspension,
			true, allowProcessInterruptAllocation,
		)
		if err != nil {
			return Statement{}, canonicalRuleStatement{}, err
		}
		if len(normalizedElse) == 0 {
			return Statement{}, canonicalRuleStatement{}, fmt.Errorf(
				"%w: %s handler else body is empty", ErrInvalidExceptionHandler, owner)
		}
		normalized.handler.Else = normalizedElse
		canonical.Handler.Else = canonicalElse
	}
	return normalized, canonical, nil
}

func canonicalizeModuleExceptionHandler(
	component *Component,
	owner string,
	handler ExceptionHandler,
	stateTypes map[string]string,
	functions map[string]*FunctionImplementation,
	allFunctions map[string]map[string]*FunctionImplementation,
) (ExceptionHandler, canonicalExceptionHandler, error) {
	block := HandleExceptions([]Statement{NullStatement()}, handler)
	normalized, canonical, err := canonicalizeExceptionHandlerBlock(
		component, owner, block, stateTypes, nil, functions, nil,
		make(map[string]bool), "module-handler/", 0, nil,
		false, false, false, false, false,
	)
	if err != nil {
		return ExceptionHandler{}, canonicalExceptionHandler{}, err
	}
	if err := validateModuleExceptionHandlerSubset(component.ID, owner, normalized.handler, allFunctions); err != nil {
		return ExceptionHandler{}, canonicalExceptionHandler{}, err
	}
	return normalized.handler, *canonical.Handler, nil
}

// The module-handler execution slice excludes constructs that create a second
// active control lifetime or suspend the handler. It retains closed state
// recovery, immediate action generation, the predefined one-argument
// Link/Unlink Context mutations, finite control, and assertions.
func validateModuleExceptionHandlerSubset(
	componentID, owner string,
	handler ExceptionHandler,
	allFunctions map[string]map[string]*FunctionImplementation,
) error {
	visitedFunctions := make(map[string]bool)
	var validate func(string, []Statement, bool) error
	var validateFunctionCall func(string, FunctionCall) error
	validateFunctionCall = func(currentComponent string, call FunctionCall) error {
		implementation := allFunctions[currentComponent][call.functionKey]
		if implementation == nil {
			return fmt.Errorf("%w: %s module handler function %q has no executable body",
				ErrInvalidExceptionHandler, owner, call.Name)
		}
		targetComponent := implementation.targetComponent
		if targetComponent == "" {
			targetComponent = currentComponent
		}
		visitKey := currentComponent + "\x00" + call.functionKey
		if !visitedFunctions[visitKey] {
			visitedFunctions[visitKey] = true
			if err := validate(targetComponent, implementation.Statements, true); err != nil {
				return err
			}
		}
		return nil
	}
	validate = func(currentComponent string, statements []Statement, inFunction bool) error {
		for _, statement := range statements {
			switch statement.kind {
			case AssignmentStatement, NullStatementKind, AssertStatementKind,
				RaiseStatementKind, ReraiseStatementKind,
				LinkStatementKind, UnlinkStatementKind:
			case ReturnStatementKind:
				if !inFunction {
					return fmt.Errorf("%w: %s module handler return has no enclosing function",
						ErrInvalidExceptionHandler, owner)
				}
			case EventCallStatement:
				if statement.timing != nil {
					return fmt.Errorf("%w: %s module handler action %q is timed",
						ErrInvalidExceptionHandler, owner, statement.output.ID)
				}
			case FunctionCallStatement:
				if err := validateFunctionCall(currentComponent, statement.functionCall); err != nil {
					return err
				}
			case DoBlockStatementKind:
				if err := validate(currentComponent, statement.handledBody, inFunction); err != nil {
					return err
				}
			case HandlerBlockStatementKind:
				for _, choice := range statement.handler.Choices {
					if choice.Action != "" || choice.Any {
						return fmt.Errorf("%w: %s nested module-handler interrupt choice is outside the immediate recovery subset",
							ErrInvalidExceptionHandler, owner)
					}
				}
				if err := validate(currentComponent, statement.handledBody, inFunction); err != nil {
					return err
				}
				for _, choice := range statement.handler.Choices {
					if err := validate(currentComponent, choice.Statements, inFunction); err != nil {
						return err
					}
				}
				if err := validate(currentComponent, statement.handler.Else, inFunction); err != nil {
					return err
				}
			case LoopStatementKind:
				if err := validate(currentComponent, statement.loopBody, inFunction); err != nil {
					return err
				}
			case ForStatementKind:
				if statement.iteratorKind != rangeStatementIteratorKind &&
					statement.iteratorKind != generatorStatementIteratorKind {
					return fmt.Errorf("%w: %s module handler iterator kind %q is outside the immediate recovery subset",
						ErrInvalidExceptionHandler, owner, statement.iteratorKind)
				}
				if err := validate(currentComponent, statement.loopBody, inFunction); err != nil {
					return err
				}
			case GeneralForStatementKind:
				for _, expression := range []ExecutableObjectExpression{
					statement.forInitial, statement.forTest, statement.forNext,
				} {
					if expression.kind == ObjectFunctionExpression {
						if err := validateFunctionCall(currentComponent, expression.call); err != nil {
							return err
						}
					}
				}
				if err := validate(currentComponent, statement.loopBody, inFunction); err != nil {
					return err
				}
			case ExitStatementKind, NextStatementKind:
				// Canonical statement validation has already resolved these to an
				// enclosing do in this statement tree. They cannot escape the
				// module-handler firing as process control.
			case IfStatementKind:
				if err := validate(currentComponent, statement.thenBranch, inFunction); err != nil {
					return err
				}
				if err := validate(currentComponent, statement.elseBranch, inFunction); err != nil {
					return err
				}
			case CaseStatementKind:
				for _, alternative := range statement.caseAlts {
					if err := validate(currentComponent, alternative.body, inFunction); err != nil {
						return err
					}
				}
				if err := validate(currentComponent, statement.caseDefault, inFunction); err != nil {
					return err
				}
			default:
				return fmt.Errorf("%w: %s module handler statement kind %q is outside the immediate recovery subset",
					ErrInvalidExceptionHandler, owner, statement.kind)
			}
		}
		return nil
	}
	for _, choice := range handler.Choices {
		if err := validate(componentID, choice.Statements, false); err != nil {
			return err
		}
	}
	return validate(componentID, handler.Else, false)
}

type raisedExceptionOccurrence struct {
	name        string
	declaration string
	event       *gorapide.Event
}

type activeInterruptHandler struct {
	id                  string
	owner               string
	processOwned        bool
	initializationOwned bool
	generationAware     bool
	handler             ExceptionHandler
	outerMatch          pattern.MatchResult
	outerSet            bool
}

type interruptHandlerInvocation struct {
	targetID   string
	eventID    gorapide.EventID
	statements []Statement
	match      pattern.MatchResult
	selection  string
}

func selectInterruptHandler(
	handlers []activeInterruptHandler,
	event *gorapide.Event,
	outer pattern.MatchResult,
) (*interruptHandlerInvocation, error) {
	return selectInterruptHandlerViews(handlers, gorapide.EventSet{event}, outer)
}

func selectInterruptHandlerViews(
	handlers []activeInterruptHandler,
	events gorapide.EventSet,
	outer pattern.MatchResult,
) (*interruptHandlerInvocation, error) {
	return selectInterruptHandlerViewsDeterministic(handlers, events, outer, nil, nil)
}

func selectInterruptHandlerViewsDeterministic(
	handlers []activeInterruptHandler,
	events gorapide.EventSet,
	outer pattern.MatchResult,
	poset pattern.PosetReader,
	choices *choiceResolver,
) (*interruptHandlerInvocation, error) {
	if len(events) == 0 {
		return nil, fmt.Errorf("%w: missing interrupt occurrence", ErrInvalidExceptionHandler)
	}
	views := append(gorapide.EventSet(nil), events...)
	sort.Slice(views, func(left, right int) bool {
		if views[left] == nil || views[right] == nil {
			return views[right] != nil
		}
		if views[left].ID != views[right].ID {
			return views[left].ID < views[right].ID
		}
		if views[left].Source != views[right].Source {
			return views[left].Source < views[right].Source
		}
		return views[left].Name < views[right].Name
	})
	for _, event := range views {
		if event == nil {
			return nil, fmt.Errorf("%w: missing interrupt occurrence", ErrInvalidExceptionHandler)
		}
	}
	candidates := make([]interruptHandlerInvocation, 0)
	for first := 0; first < len(views); {
		last := first + 1
		for last < len(views) && views[last].ID == views[first].ID {
			last++
		}
		for handlerIndex := len(handlers) - 1; handlerIndex >= 0; handlerIndex-- {
			active := handlers[handlerIndex]
			occurrenceCandidates := make([]interruptHandlerInvocation, 0)
			seen := make(map[string]bool)
			activeOuter := outer
			if active.outerSet {
				activeOuter = cloneProcessMatch(active.outerMatch)
			}
			for _, event := range views[first:last] {
				if active.owner != "" && event.Source != active.owner {
					continue
				}
				for _, choice := range active.handler.Choices {
					if !choice.Any && (choice.Action == "" || choice.Action != event.Name) {
						continue
					}
					handlerMatch := pattern.MatchResult{
						Events:   append(gorapide.EventSet(nil), activeOuter.Events...),
						Bindings: append(pattern.Bindings(nil), activeOuter.Bindings...),
					}
					if !handlerMatch.Events.Contains(event.ID) {
						handlerMatch.Events = append(handlerMatch.Events, event)
					}
					for _, binding := range choice.Bindings {
						value, exists := event.Param(binding.Formal)
						if !exists {
							return nil, fmt.Errorf("%w: interrupt action %q has no parameter %q",
								ErrInvalidExceptionHandler, event.Name, binding.Formal)
						}
						handlerMatch.Bindings = append(handlerMatch.Bindings, pattern.Binding{
							Placeholder: binding.Placeholder, Value: value,
						})
					}
					sort.Slice(handlerMatch.Bindings, func(left, right int) bool {
						return handlerMatch.Bindings[left].Placeholder < handlerMatch.Bindings[right].Placeholder
					})
					selection := active.id + "\x00" + exceptionHandlerChoiceKey(choice) +
						"\x00" + string(event.ID) + "\x00" + event.Source + "\x00" + event.Name
					if seen[selection] {
						continue
					}
					seen[selection] = true
					occurrenceCandidates = append(occurrenceCandidates, interruptHandlerInvocation{
						targetID: active.id, eventID: event.ID,
						statements: copyStatements(choice.Statements),
						match:      handlerMatch, selection: selection,
					})
				}
			}
			if len(occurrenceCandidates) != 0 {
				// The newest active handler wins for every qualified view of one
				// occurrence. An older enclosing handler cannot compete merely
				// because it names a different basic-connection observation.
				candidates = append(candidates, occurrenceCandidates...)
				break
			}
		}
		first = last
	}
	if len(candidates) == 0 {
		return nil, nil
	}

	earliest := make([]interruptHandlerInvocation, 0, len(candidates))
	for index, candidate := range candidates {
		later := false
		if poset != nil {
			for otherIndex, other := range candidates {
				if index == otherIndex || candidate.eventID == other.eventID {
					continue
				}
				if poset.IsCausallyBefore(other.eventID, candidate.eventID) {
					later = true
					break
				}
			}
		}
		if !later {
			earliest = append(earliest, candidate)
		}
	}
	sort.Slice(earliest, func(left, right int) bool {
		return earliest[left].selection < earliest[right].selection
	})
	if len(earliest) == 1 {
		return &earliest[0], nil
	}
	if choices == nil {
		return nil, fmt.Errorf(
			"%w: %d causally earliest generation-time interrupt matches require an explicit semantic choice",
			ErrInvalidExceptionHandler, len(earliest),
		)
	}
	options := make([]string, len(earliest))
	bySelection := make(map[string]int, len(earliest))
	for index, candidate := range earliest {
		options[index] = candidate.selection
		bySelection[candidate.selection] = index
	}
	selected, err := choices.resolve("generation-time-interrupt", options)
	if err != nil {
		return nil, err
	}
	result := earliest[bySelection[selected]]
	return &result, nil
}

func selectExceptionHandler(
	handler ExceptionHandler,
	raised *raisedExceptionOccurrence,
	outer pattern.MatchResult,
) ([]Statement, pattern.MatchResult, bool, error) {
	if raised == nil || raised.event == nil {
		return nil, pattern.MatchResult{}, false, fmt.Errorf("%w: missing raised occurrence", ErrInvalidExceptionHandler)
	}
	handlerMatch := pattern.MatchResult{
		Events:   append(gorapide.EventSet(nil), outer.Events...),
		Bindings: append(pattern.Bindings(nil), outer.Bindings...),
	}
	if !handlerMatch.Events.Contains(raised.event.ID) {
		handlerMatch.Events = append(handlerMatch.Events, raised.event)
	}
	for _, choice := range handler.Choices {
		if !choice.Any && (choice.Exception != raised.name ||
			choice.ExceptionDeclaration != raised.declaration) {
			continue
		}
		for _, binding := range choice.Bindings {
			value, exists := raised.event.Param(binding.Formal)
			if !exists {
				return nil, pattern.MatchResult{}, false, fmt.Errorf(
					"%w: exception %q has no parameter %q", ErrInvalidExceptionHandler, raised.name, binding.Formal)
			}
			handlerMatch.Bindings = append(handlerMatch.Bindings, pattern.Binding{
				Placeholder: binding.Placeholder, Value: value,
			})
		}
		sort.Slice(handlerMatch.Bindings, func(left, right int) bool {
			return handlerMatch.Bindings[left].Placeholder < handlerMatch.Bindings[right].Placeholder
		})
		return choice.Statements, handlerMatch, true, nil
	}
	if handler.Else != nil {
		return handler.Else, handlerMatch, true, nil
	}
	return nil, pattern.MatchResult{}, false, nil
}

type moduleExceptionHandlerInvocation struct {
	statements []Statement
	match      pattern.MatchResult
	selection  string
}

func selectModuleExceptionHandler(
	handler ExceptionHandler,
	raised *raisedExceptionOccurrence,
	_ string,
) (*moduleExceptionHandlerInvocation, error) {
	statements, match, handled, err := selectExceptionHandler(
		handler, raised, pattern.MatchResult{Events: gorapide.EventSet{}, Bindings: pattern.Bindings{}},
	)
	if err != nil || !handled {
		return nil, err
	}
	selection := "else"
	if len(handler.Choices) != 0 {
		for _, choice := range handler.Choices {
			if choice.Exception == raised.name && choice.ExceptionDeclaration == raised.declaration {
				selection = "exception:" + choice.ExceptionDeclaration
				break
			}
		}
	}
	return &moduleExceptionHandlerInvocation{
		statements: copyStatements(statements), match: match, selection: selection,
	}, nil
}
