package arch

import (
	"errors"
	"fmt"
	"sort"

	"github.com/ShaneDolphin/gorapide"
	"github.com/ShaneDolphin/gorapide/pattern"
)

var ErrInvalidDeclarativeRule = errors.New("invalid declarative Rapide transition rule")

// RuleProcessKind is the process generated by a Rapide transition rule.
// A pipe process orders successive outputs; an agent process does not.
type RuleProcessKind int

const (
	RulePipeProcess RuleProcessKind = iota + 1
	RuleAgentProcess
)

func (kind RuleProcessKind) String() string {
	switch kind {
	case RulePipeProcess:
		return "Pipe"
	case RuleAgentProcess:
		return "Agent"
	default:
		return fmt.Sprintf("RuleProcessKind(%d)", int(kind))
	}
}

type RuleValueKind string

const (
	RuleLiteralValue RuleValueKind = "literal"
	RuleBindingValue RuleValueKind = "binding"
	RuleStateValue   RuleValueKind = "state"
	RuleSelfValue    RuleValueKind = "self"
	RuleNewValue     RuleValueKind = "new"
	RuleUnaryValue   RuleValueKind = "unary"
	RuleBinaryValue  RuleValueKind = "binary"
	RuleTernaryValue RuleValueKind = "ternary"
)

// RuleValue is a closed, serializable expression used in a rule output.
// The initial expression subset is deliberately small: a canonical literal or
// a placeholder established by the trigger pattern.
type RuleValue struct {
	kind                       RuleValueKind
	literal                    any
	placeholder                string
	state                      string
	selfType                   string
	newType                    string
	newArguments               []ModuleGeneratorArgument
	newInitializationArguments []ModuleInitializationArgument
	operator                   RuleValueOperator
	operands                   []RuleValue
}

// LiteralValue returns a canonical-literal rule expression.
func LiteralValue(value any) RuleValue {
	return RuleValue{kind: RuleLiteralValue, literal: value}
}

// BoundValue returns a reference to a trigger placeholder.
func BoundValue(placeholder string) RuleValue {
	return RuleValue{kind: RuleBindingValue, placeholder: placeholder}
}

// ReadState returns a closed expression that dereferences module state.
func ReadState(name string) RuleValue {
	return RuleValue{kind: RuleStateValue, state: name}
}

// ModuleSelfValue denotes Stanford Rapide's tool-supplied Self object for the
// currently executing module. typeName is its exact enclosing interface type.
func ModuleSelfValue(typeName string) RuleValue {
	return RuleValue{kind: RuleSelfValue, selfType: typeName}
}

// ModuleNewValue denotes a call to the tool-supplied, owner-only allocator of
// the currently executing module. Allocation is an effect and is therefore
// evaluated only as an immediate generated-action actual by the statement
// kernel, never by the side-effect-free expression evaluator.
func ModuleNewValue(typeName string) RuleValue {
	return RuleValue{kind: RuleNewValue, newType: typeName}
}

// ModuleNewValueWithArguments denotes New applied to the complete ordered
// module-generator actual list selected by the allocator call. Arguments are
// canonicalized with the enclosing model and are checked against the owning
// component's already-elaborated generator specialization before allocation.
func ModuleNewValueWithArguments(typeName string, arguments ...ModuleGeneratorArgument) RuleValue {
	return RuleValue{
		kind: RuleNewValue, newType: typeName,
		newArguments: append([]ModuleGeneratorArgument(nil), arguments...),
	}
}

// ModuleNewValueWithInitializationArguments retains both the exact compiled
// generator specialization and the complete ordered initialization actuals.
func ModuleNewValueWithInitializationArguments(
	typeName string,
	generatorArguments []ModuleGeneratorArgument,
	initializationArguments ...ModuleInitializationArgument,
) RuleValue {
	return RuleValue{
		kind: RuleNewValue, newType: typeName,
		newArguments:               append([]ModuleGeneratorArgument(nil), generatorArguments...),
		newInitializationArguments: copyModuleInitializationArguments(initializationArguments),
	}
}

// RuleParameter maps one output parameter to a closed rule expression.
type RuleParameter struct {
	Name  string
	Value RuleValue
}

// LiteralParam declares an output parameter with a constant value.
func LiteralParam(name string, value any) RuleParameter {
	return RuleParameter{Name: name, Value: LiteralValue(value)}
}

// BindingParam declares an output parameter taken from a trigger placeholder.
func BindingParam(name, placeholder string) RuleParameter {
	return RuleParameter{Name: name, Value: BoundValue(placeholder)}
}

// StateParam declares an output parameter read from module state.
func StateParam(name, state string) RuleParameter {
	return RuleParameter{Name: name, Value: ReadState(state)}
}

// ExpressionParam declares an output parameter computed by a closed expression.
func ExpressionParam(name string, value RuleValue) RuleParameter {
	return RuleParameter{Name: name, Value: copyRuleValue(value)}
}

// RuleOutput is one locally identified event in a closed rule-body poset.
// Causes names direct predecessors in the same body. Trigger and pipe-frontier
// dependencies are added by the engine to the roots of the body.
type RuleOutput struct {
	ID         string
	Action     string
	Parameters []RuleParameter
	Causes     []string
	// Equivalent names other local outputs in the same causal-equivalence
	// class. It is currently admitted only by deterministic map generators.
	Equivalent []string
}

// RuleEvent constructs one event declaration in a rule-body poset.
func RuleEvent(id, action string, parameters ...RuleParameter) RuleOutput {
	return RuleOutput{ID: id, Action: action, Parameters: append([]RuleParameter(nil), parameters...)}
}

// After returns a copy whose direct body predecessors are local output IDs.
func (output RuleOutput) After(causes ...string) RuleOutput {
	output.Parameters = append([]RuleParameter(nil), output.Parameters...)
	output.Causes = append([]string(nil), causes...)
	output.Equivalent = append([]string(nil), output.Equivalent...)
	return output
}

// EquivalentTo returns a copy causally equivalent to the named local outputs.
// Deterministic validation closes the declaration symmetrically and
// transitively and rejects any strict path within the resulting class.
func (output RuleOutput) EquivalentTo(ids ...string) RuleOutput {
	output.Parameters = append([]RuleParameter(nil), output.Parameters...)
	output.Causes = append([]string(nil), output.Causes...)
	output.Equivalent = append([]string(nil), ids...)
	return output
}

// RuleBody is a finite restricted poset generator. An empty Outputs slice is a
// valid null body that consumes its trigger without generating an event.
// Alternatives is reserved for a finite set of complete generator posets whose
// selection is language-permitted. The deterministic architecture executor
// rejects it; the map executor gives it an explicit schedule and exploration
// witness.
type RuleBody struct {
	Assignments  []StateAssignment
	Outputs      []RuleOutput
	Alternatives [][]RuleOutput
	Statements   []Statement
}

// DeclarativeRule is the closed Go representation of a Rapide transition
// rule. It contains no callback and is therefore part of canonical model
// identity and deterministic replay.
type DeclarativeRule struct {
	ID      string
	Trigger pattern.Pattern
	Guard   *RuleValue
	Process RuleProcessKind
	Body    *RuleBody

	// allowProcessDoControl is set only while validating the body of a
	// source-equivalent when state. It is deliberately not a public rule option.
	allowProcessDoControl bool
	processDoName         string
	allowTimingSuspension bool
	// allowProcessInterruptAllocation is validation-only authority for a
	// process-owned handler body to execute New through the retained
	// generation-time continuation. Declarative rules, functions, initial/final
	// parts, and other handler owners do not receive this authority.
	allowProcessInterruptAllocation bool
	// initializationOwned marks the synthetic rule used to execute a module
	// initial part. It is execution-only authority for a synchronous handler to
	// cross New; it is not serialized as a user-selectable rule property.
	initializationOwned bool
	// allowGeneratorCausalEquivalence is validation-only authority used by the
	// deterministic map model. Generic architecture execution still rejects
	// equivalent generator outputs until that producer path is implemented.
	allowGeneratorCausalEquivalence bool
}

// DeclarativeRuleBuilder constructs a closed transition declaration.
type DeclarativeRuleBuilder struct {
	rule DeclarativeRule
}

// Rule begins a declarative transition rule. Pipe is the default process,
// matching Rapide's => transition operator.
func Rule(id string) *DeclarativeRuleBuilder {
	return &DeclarativeRuleBuilder{rule: DeclarativeRule{ID: id, Process: RulePipeProcess}}
}

// On sets the event-pattern trigger.
func (builder *DeclarativeRuleBuilder) On(trigger pattern.Pattern) *DeclarativeRuleBuilder {
	builder.rule.Trigger = trigger
	return builder
}

// Where adds a closed, side-effect-free Boolean guard. State dereferences are
// evaluated at generation of the last event in the selected trigger match.
func (builder *DeclarativeRuleBuilder) Where(guard RuleValue) *DeclarativeRuleBuilder {
	copy := copyRuleValue(guard)
	builder.rule.Guard = &copy
	return builder
}

// Pipe selects Rapide's => pipe-process transition semantics.
func (builder *DeclarativeRuleBuilder) Pipe() *DeclarativeRuleBuilder {
	builder.rule.Process = RulePipeProcess
	return builder
}

// Agent selects Rapide's ||> agent-process transition semantics.
func (builder *DeclarativeRuleBuilder) Agent() *DeclarativeRuleBuilder {
	builder.rule.Process = RuleAgentProcess
	return builder
}

// Emit declares a single-event body. Generate expresses a multi-event poset.
func (builder *DeclarativeRuleBuilder) Emit(action string, parameters ...RuleParameter) *DeclarativeRuleBuilder {
	body := ensureRuleBody(builder.rule.Body)
	body.Outputs = []RuleOutput{RuleEvent("result", action, parameters...)}
	body.Alternatives = nil
	builder.rule.Body = body
	return builder
}

// Generate declares the finite restricted poset generated by each firing.
// Output slice order has no semantic meaning; local IDs and Causes define it.
func (builder *DeclarativeRuleBuilder) Generate(outputs ...RuleOutput) *DeclarativeRuleBuilder {
	body := ensureRuleBody(builder.rule.Body)
	body.Alternatives = nil
	body.Outputs = make([]RuleOutput, len(outputs))
	for i, output := range outputs {
		body.Outputs[i] = copyRuleOutput(output)
	}
	builder.rule.Body = body
	return builder
}

// GenerateOneOf declares every complete finite poset that this body may
// generate. Alternative and output slice order have no semantic meaning.
// Selection is performed only by an execution surface that records an
// explicit deterministic choice witness.
func (builder *DeclarativeRuleBuilder) GenerateOneOf(alternatives ...[]RuleOutput) *DeclarativeRuleBuilder {
	body := ensureRuleBody(builder.rule.Body)
	body.Outputs = nil
	body.Alternatives = make([][]RuleOutput, len(alternatives))
	for alternativeIndex, alternative := range alternatives {
		body.Alternatives[alternativeIndex] = make([]RuleOutput, len(alternative))
		for outputIndex, output := range alternative {
			body.Alternatives[alternativeIndex][outputIndex] = copyRuleOutput(output)
		}
	}
	if len(body.Alternatives) != 0 {
		body.Outputs = make([]RuleOutput, len(body.Alternatives[0]))
		for index, output := range body.Alternatives[0] {
			body.Outputs[index] = copyRuleOutput(output)
		}
	}
	builder.rule.Body = body
	return builder
}

// NoEvents declares a null body that consumes the trigger match but generates
// no event occurrence.
func (builder *DeclarativeRuleBuilder) NoEvents() *DeclarativeRuleBuilder {
	body := ensureRuleBody(builder.rule.Body)
	body.Outputs = []RuleOutput{}
	body.Alternatives = nil
	builder.rule.Body = body
	return builder
}

// Do declares a sequential ordinary-statement body. It is mutually exclusive
// with the restricted assignment-plus-poset generator shorthands.
func (builder *DeclarativeRuleBuilder) Do(statements ...Statement) *DeclarativeRuleBuilder {
	builder.rule.Body = &RuleBody{Statements: copyStatements(statements)}
	return builder
}

// Assign declares sequential state assignments performed before the body event
// generator. Assignment order is semantic and is therefore preserved.
func (builder *DeclarativeRuleBuilder) Assign(assignments ...StateAssignment) *DeclarativeRuleBuilder {
	body := ensureRuleBody(builder.rule.Body)
	for _, assignment := range assignments {
		body.Assignments = append(body.Assignments, StateAssignment{
			Target: assignment.Target, Value: copyRuleValue(assignment.Value),
		})
	}
	builder.rule.Body = body
	return builder
}

// Build returns an isolated declaration snapshot.
func (builder *DeclarativeRuleBuilder) Build() *DeclarativeRule {
	if builder == nil {
		return nil
	}
	result := builder.rule
	result.Guard = copyRuleValuePointer(builder.rule.Guard)
	result.Body = copyRuleBody(builder.rule.Body)
	return &result
}

// AddDeclarativeRule registers a closed transition declaration on a component.
// Complete semantic validation occurs when the canonical model is built.
func (component *Component) AddDeclarativeRule(rule *DeclarativeRule) error {
	if component == nil || rule == nil {
		return fmt.Errorf("%w: component or rule is nil", ErrInvalidDeclarativeRule)
	}
	copy := *rule
	copy.Guard = copyRuleValuePointer(rule.Guard)
	copy.Body = copyRuleBody(rule.Body)
	component.mu.Lock()
	component.transitions = append(component.transitions, &copy)
	component.mu.Unlock()
	return nil
}

type canonicalRuleParameter struct {
	Name                    string                                  `json:"name"`
	Kind                    RuleValueKind                           `json:"kind"`
	Placeholder             string                                  `json:"placeholder,omitempty"`
	State                   string                                  `json:"state,omitempty"`
	Type                    string                                  `json:"type,omitempty"`
	GeneratorArguments      []canonicalArchitectureArgument         `json:"generator_arguments,omitempty"`
	InitializationArguments []canonicalModuleInitializationArgument `json:"initialization_arguments,omitempty"`
	Literal                 *gorapide.CanonicalValue                `json:"literal,omitempty"`
	Operator                RuleValueOperator                       `json:"operator,omitempty"`
	Operands                []canonicalRuleValue                    `json:"operands,omitempty"`
}

type canonicalRuleOutput struct {
	ID         string                   `json:"id"`
	Action     string                   `json:"action"`
	Parameters []canonicalRuleParameter `json:"parameters"`
	Causes     []string                 `json:"causes"`
	Equivalent []string                 `json:"equivalent,omitempty"`
}

type canonicalDeclarativeRule struct {
	ID          string                     `json:"id"`
	Trigger     string                     `json:"trigger"`
	Guard       *canonicalRuleValue        `json:"guard,omitempty"`
	Process     int                        `json:"process"`
	Assignments []canonicalStateAssignment `json:"assignments"`
	Outputs     []canonicalRuleOutput      `json:"outputs"`
	Statements  []canonicalRuleStatement   `json:"statements,omitempty"`
}

func canonicalizeDeclarativeRule(component *Component, declaration *DeclarativeRule, stateTypes map[string]string, functions map[string]*FunctionImplementation) (*DeclarativeRule, canonicalDeclarativeRule, error) {
	if declaration == nil || declaration.ID == "" {
		return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule has no stable identity", ErrInvalidDeclarativeRule)
	}
	if declaration.Process != RulePipeProcess && declaration.Process != RuleAgentProcess {
		return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q has process %d", ErrInvalidDeclarativeRule, declaration.ID, declaration.Process)
	}
	if declaration.Body == nil {
		return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q has no declared body", ErrInvalidDeclarativeRule, declaration.ID)
	}
	if declaration.Body.Alternatives != nil {
		return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q has arbitrary generator alternatives outside map choice execution", ErrInvalidDeclarativeRule, declaration.ID)
	}
	triggerKey, err := pattern.DeterministicKey(declaration.Trigger)
	if err != nil {
		return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q trigger: %v", ErrInvalidDeclarativeRule, declaration.ID, err)
	}
	trigger, err := pattern.CloneDeterministic(declaration.Trigger)
	if err != nil {
		return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q trigger: %v", ErrInvalidDeclarativeRule, declaration.ID, err)
	}
	placeholderTypes, err := pattern.BoundPlaceholderTypes(declaration.Trigger)
	if err != nil {
		return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q trigger: %v", ErrInvalidDeclarativeRule, declaration.ID, err)
	}
	bound := make(map[string]bool, len(placeholderTypes))
	for name := range placeholderTypes {
		bound[name] = true
	}

	normalized := *declaration
	normalized.Trigger = trigger
	normalized.Guard = nil
	normalized.Body = &RuleBody{Outputs: make([]RuleOutput, 0, len(declaration.Body.Outputs))}
	canonical := canonicalDeclarativeRule{
		ID: declaration.ID, Trigger: triggerKey, Process: int(declaration.Process),
		Outputs: make([]canonicalRuleOutput, 0, len(declaration.Body.Outputs)),
	}
	if declaration.Guard != nil {
		normalizedGuard, canonicalGuard, guardType, err := canonicalizeClosedRuleValue(
			"rule "+declaration.ID+" guard", *declaration.Guard, stateTypes, placeholderTypes,
		)
		if err != nil {
			return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: %w", ErrInvalidDeclarativeRule, err)
		}
		if guardType != "" && guardType != "Boolean" {
			return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q guard has type %s, want Boolean", ErrInvalidDeclarativeRule, declaration.ID, guardType)
		}
		normalized.Guard = &normalizedGuard
		canonical.Guard = &canonicalGuard
	}
	normalizedAssignments, canonicalAssignments, err := canonicalizeStateAssignments(
		"rule "+declaration.ID, declaration.Body.Assignments, stateTypes, placeholderTypes,
	)
	if err != nil {
		return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: %w", ErrInvalidDeclarativeRule, err)
	}
	normalized.Body.Assignments = normalizedAssignments
	canonical.Assignments = canonicalAssignments
	if declaration.Body.Statements != nil {
		if len(declaration.Body.Assignments) != 0 || declaration.Body.Outputs != nil {
			return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q mixes ordinary statements with a restricted generator body", ErrInvalidDeclarativeRule, declaration.ID)
		}
		normalizedStatements, canonicalStatements, err := canonicalizeRuleStatementsWithProcessExit(
			component, "rule "+declaration.ID, declaration.Body.Statements, stateTypes, placeholderTypes, functions, nil,
			declaration.allowProcessDoControl, declaration.processDoName, declaration.allowTimingSuspension,
			declaration.allowProcessInterruptAllocation,
		)
		if err != nil {
			return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: %w", ErrInvalidDeclarativeRule, err)
		}
		normalized.Body.Statements = normalizedStatements
		canonical.Statements = canonicalStatements
		return &normalized, canonical, nil
	}
	seenOutputs := make(map[string]bool, len(declaration.Body.Outputs))
	for _, output := range declaration.Body.Outputs {
		if output.ID == "" || seenOutputs[output.ID] {
			return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q has empty or duplicate body output ID %q", ErrInvalidDeclarativeRule, declaration.ID, output.ID)
		}
		if output.Action == "" {
			return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q output %q has no action", ErrInvalidDeclarativeRule, declaration.ID, output.ID)
		}
		seenOutputs[output.ID] = true
		normalizedOutput := RuleOutput{ID: output.ID, Action: output.Action}
		canonicalOutput := canonicalRuleOutput{ID: output.ID, Action: output.Action}
		seenParameters := make(map[string]bool, len(output.Parameters))
		for _, parameter := range output.Parameters {
			normalizedParameter, canonicalParameter, err := canonicalizeRuleParameter(
				declaration.ID, output.ID, parameter, bound, seenParameters, stateTypes, placeholderTypes,
			)
			if err != nil {
				return nil, canonicalDeclarativeRule{}, err
			}
			normalizedOutput.Parameters = append(normalizedOutput.Parameters, normalizedParameter)
			canonicalOutput.Parameters = append(canonicalOutput.Parameters, canonicalParameter)
		}
		sort.Slice(normalizedOutput.Parameters, func(i, j int) bool { return normalizedOutput.Parameters[i].Name < normalizedOutput.Parameters[j].Name })
		sort.Slice(canonicalOutput.Parameters, func(i, j int) bool { return canonicalOutput.Parameters[i].Name < canonicalOutput.Parameters[j].Name })
		causes := append([]string(nil), output.Causes...)
		sort.Strings(causes)
		write := 0
		for _, cause := range causes {
			if cause == "" || cause == output.ID {
				return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q output %q has empty or self cause %q", ErrInvalidDeclarativeRule, declaration.ID, output.ID, cause)
			}
			if write > 0 && causes[write-1] == cause {
				continue
			}
			causes[write] = cause
			write++
		}
		normalizedOutput.Causes = append([]string(nil), causes[:write]...)
		canonicalOutput.Causes = append([]string(nil), causes[:write]...)
		equivalent := append([]string(nil), output.Equivalent...)
		sort.Strings(equivalent)
		write = 0
		for _, peer := range equivalent {
			if peer == "" || peer == output.ID {
				return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q output %q has empty or self causal-equivalence peer %q", ErrInvalidDeclarativeRule, declaration.ID, output.ID, peer)
			}
			if write > 0 && equivalent[write-1] == peer {
				continue
			}
			equivalent[write] = peer
			write++
		}
		normalizedOutput.Equivalent = append([]string(nil), equivalent[:write]...)
		canonicalOutput.Equivalent = append([]string(nil), equivalent[:write]...)
		if len(normalizedOutput.Equivalent) != 0 && !declaration.allowGeneratorCausalEquivalence {
			return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q output %q uses causal equivalence outside map generator execution", ErrInvalidDeclarativeRule, declaration.ID, output.ID)
		}
		if !ruleOutputShapeMatches(component, normalizedOutput, stateTypes, placeholderTypes) {
			return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q output %q action %s does not match a declared out-action shape", ErrInvalidDeclarativeRule, declaration.ID, output.ID, output.Action)
		}
		normalized.Body.Outputs = append(normalized.Body.Outputs, normalizedOutput)
		canonical.Outputs = append(canonical.Outputs, canonicalOutput)
	}
	for _, output := range normalized.Body.Outputs {
		for _, cause := range output.Causes {
			if !seenOutputs[cause] {
				return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q output %q references missing body cause %q", ErrInvalidDeclarativeRule, declaration.ID, output.ID, cause)
			}
		}
		for _, peer := range output.Equivalent {
			if !seenOutputs[peer] {
				return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q output %q references missing causal-equivalence peer %q", ErrInvalidDeclarativeRule, declaration.ID, output.ID, peer)
			}
		}
	}
	sort.Slice(normalized.Body.Outputs, func(i, j int) bool { return normalized.Body.Outputs[i].ID < normalized.Body.Outputs[j].ID })
	sort.Slice(canonical.Outputs, func(i, j int) bool { return canonical.Outputs[i].ID < canonical.Outputs[j].ID })
	if _, err := ruleBodyOrder(normalized.Body.Outputs); err != nil {
		return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q: %v", ErrInvalidDeclarativeRule, declaration.ID, err)
	}
	if err := normalizeRuleOutputEquivalences(normalized.Body.Outputs); err != nil {
		return nil, canonicalDeclarativeRule{}, fmt.Errorf("%w: rule %q: %v", ErrInvalidDeclarativeRule, declaration.ID, err)
	}
	for index := range normalized.Body.Outputs {
		canonical.Outputs[index].Equivalent = append([]string(nil), normalized.Body.Outputs[index].Equivalent...)
	}
	return &normalized, canonical, nil
}

func canonicalizeRuleParameter(ruleID, outputID string, parameter RuleParameter, bound, seen map[string]bool, stateTypes, placeholderTypes map[string]string) (RuleParameter, canonicalRuleParameter, error) {
	if parameter.Name == "" || seen[parameter.Name] {
		return RuleParameter{}, canonicalRuleParameter{}, fmt.Errorf("%w: rule %q output %q has empty or duplicate parameter %q", ErrInvalidDeclarativeRule, ruleID, outputID, parameter.Name)
	}
	seen[parameter.Name] = true
	effectivePlaceholderTypes := make(map[string]string, len(bound)+len(placeholderTypes))
	for name := range bound {
		effectivePlaceholderTypes[name] = ""
	}
	for name, typeName := range placeholderTypes {
		effectivePlaceholderTypes[name] = typeName
	}
	normalizedValue, expression, _, err := canonicalizeClosedRuleValue(
		"rule "+ruleID+" output "+outputID+" parameter "+parameter.Name,
		parameter.Value, stateTypes, effectivePlaceholderTypes,
	)
	if err != nil {
		return RuleParameter{}, canonicalRuleParameter{}, fmt.Errorf("%w: %w", ErrInvalidDeclarativeRule, err)
	}
	return RuleParameter{Name: parameter.Name, Value: normalizedValue}, canonicalRuleParameter{
		Name: parameter.Name, Kind: expression.Kind, Placeholder: expression.Placeholder,
		State: expression.State, Type: expression.Type,
		GeneratorArguments:      expression.GeneratorArguments,
		InitializationArguments: expression.InitializationArguments, Literal: expression.Literal,
		Operator: expression.Operator, Operands: expression.Operands,
	}, nil
}

func ruleOutputShapeMatches(component *Component, output RuleOutput, stateTypes, placeholderTypes map[string]string) bool {
	return ruleOutputShapeMatchesKinds(component, output, stateTypes, placeholderTypes, OutAction, PrivateAction)
}

func ruleOutputShapeMatchesKinds(
	component *Component,
	output RuleOutput,
	stateTypes, placeholderTypes map[string]string,
	kinds ...ActionKind,
) bool {
	if component == nil || component.Interface == nil {
		return false
	}
	acceptedKinds := make(map[ActionKind]bool, len(kinds))
	for _, kind := range kinds {
		acceptedKinds[kind] = true
	}
	actions := append([]ActionDecl(nil), component.Interface.Actions...)
	for _, service := range component.Interface.Services {
		actions = append(actions, service.Actions...)
	}
	for _, action := range actions {
		if action.Name != output.Action || !acceptedKinds[action.Kind] || len(action.Params) != len(output.Parameters) {
			continue
		}
		declarations := make(map[string]ParamDecl, len(action.Params))
		for _, parameter := range action.Params {
			declarations[parameter.Name] = parameter
		}
		matches := true
		for _, parameter := range output.Parameters {
			declaration, ok := declarations[parameter.Name]
			if !ok {
				matches = false
				break
			}
			_, _, expressionType, err := canonicalizeClosedRuleValue(
				"output "+output.ID+" parameter "+parameter.Name,
				parameter.Value, stateTypes, placeholderTypes,
			)
			if _, structural := declaration.StructuralRapideType(); structural {
				// An untyped pattern binding has already been constrained by the
				// matched action declaration.  Source compilation checks the
				// placeholder's named interface type against that declaration;
				// the pattern package intentionally records only predefined value
				// constraints.  Preserve that closed-world fact here while still
				// requiring exact types for Self, New, and other typed values.
				matches = err == nil && (expressionType == declaration.Type ||
					(expressionType == "" && parameter.Value.kind == RuleBindingValue))
				if parameter.Value.kind == RuleLiteralValue {
					matches = matches && valueMatchesParameter(parameter.Value.literal, declaration)
				}
			} else {
				matches = err == nil && (expressionType == "" || ruleValueAssignableToPredefined(parameter.Value, expressionType, declaration.Type))
				if parameter.Value.kind == RuleLiteralValue {
					matches = err == nil && valueMatchesPredefinedType(parameter.Value.literal, declaration.Type)
				}
			}
			if !matches {
				break
			}
		}
		if matches {
			return true
		}
	}
	return false
}

func resolveRuleParameters(ruleID string, output RuleOutput, bindings pattern.Bindings, cells map[string]*stateCell) (map[string]any, []StateReadRecord, []gorapide.EventID, error) {
	parameters := make(map[string]any, len(output.Parameters))
	reads := make([]StateReadRecord, 0)
	var readCauses []gorapide.EventID
	for _, parameter := range output.Parameters {
		value, causes, expressionReads, err := evaluateRuleValue("rule "+ruleID+" output "+output.ID, parameter.Value, bindings, cells)
		if err != nil {
			return nil, nil, nil, err
		}
		parameters[parameter.Name] = value
		readCauses = append(readCauses, causes...)
		reads = append(reads, expressionReads...)
	}
	canonical, err := gorapide.CanonicalizeParams(parameters)
	return canonical, reads, canonicalEventIDs(readCauses), err
}

func copyRuleBody(body *RuleBody) *RuleBody {
	if body == nil {
		return nil
	}
	copy := &RuleBody{
		Assignments: make([]StateAssignment, len(body.Assignments)),
		Statements:  copyStatements(body.Statements),
	}
	if body.Outputs != nil {
		copy.Outputs = make([]RuleOutput, len(body.Outputs))
	}
	for i, assignment := range body.Assignments {
		copy.Assignments[i] = StateAssignment{Target: assignment.Target, Value: copyRuleValue(assignment.Value)}
	}
	for i, output := range body.Outputs {
		copy.Outputs[i] = copyRuleOutput(output)
	}
	if body.Alternatives != nil {
		copy.Alternatives = make([][]RuleOutput, len(body.Alternatives))
		for alternativeIndex, alternative := range body.Alternatives {
			copy.Alternatives[alternativeIndex] = make([]RuleOutput, len(alternative))
			for outputIndex, output := range alternative {
				copy.Alternatives[alternativeIndex][outputIndex] = copyRuleOutput(output)
			}
		}
	}
	return copy
}

func ensureRuleBody(body *RuleBody) *RuleBody {
	if body == nil {
		return &RuleBody{}
	}
	return copyRuleBody(body)
}

func copyRuleOutput(output RuleOutput) RuleOutput {
	output.Parameters = append([]RuleParameter(nil), output.Parameters...)
	for i := range output.Parameters {
		output.Parameters[i].Value = copyRuleValue(output.Parameters[i].Value)
	}
	output.Causes = append([]string(nil), output.Causes...)
	output.Equivalent = append([]string(nil), output.Equivalent...)
	return output
}

func normalizeRuleOutputEquivalences(outputs []RuleOutput) error {
	parent := make(map[string]string, len(outputs))
	for _, output := range outputs {
		parent[output.ID] = output.ID
	}
	var find func(string) string
	find = func(id string) string {
		if parent[id] != id {
			parent[id] = find(parent[id])
		}
		return parent[id]
	}
	union := func(left, right string) {
		left, right = find(left), find(right)
		if left == right {
			return
		}
		if right < left {
			left, right = right, left
		}
		parent[right] = left
	}
	for _, output := range outputs {
		for _, peer := range output.Equivalent {
			union(output.ID, peer)
		}
	}
	classes := make(map[string][]string)
	for id := range parent {
		representative := find(id)
		classes[representative] = append(classes[representative], id)
	}
	for representative := range classes {
		sort.Strings(classes[representative])
	}

	children := make(map[string][]string, len(outputs))
	for _, output := range outputs {
		for _, cause := range output.Causes {
			children[cause] = append(children[cause], output.ID)
		}
	}
	canReach := func(start, target string) bool {
		seen := make(map[string]bool)
		queue := []string{start}
		for len(queue) != 0 {
			current := queue[0]
			queue = queue[1:]
			if seen[current] {
				continue
			}
			seen[current] = true
			for _, child := range children[current] {
				if child == target {
					return true
				}
				queue = append(queue, child)
			}
		}
		return false
	}
	for _, members := range classes {
		for leftIndex, left := range members {
			for _, right := range members[leftIndex+1:] {
				if canReach(left, right) || canReach(right, left) {
					return fmt.Errorf("causal-equivalence class contains strictly ordered outputs %q and %q", left, right)
				}
			}
		}
	}
	for index := range outputs {
		members := classes[find(outputs[index].ID)]
		outputs[index].Equivalent = outputs[index].Equivalent[:0]
		for _, member := range members {
			if member != outputs[index].ID {
				outputs[index].Equivalent = append(outputs[index].Equivalent, member)
			}
		}
	}
	return nil
}

func ruleBodyOrder(outputs []RuleOutput) ([]RuleOutput, error) {
	byID := make(map[string]RuleOutput, len(outputs))
	degree := make(map[string]int, len(outputs))
	children := make(map[string][]string, len(outputs))
	for _, output := range outputs {
		byID[output.ID] = output
		degree[output.ID] = len(output.Causes)
		for _, cause := range output.Causes {
			children[cause] = append(children[cause], output.ID)
		}
	}
	for id := range children {
		sort.Strings(children[id])
	}
	ready := make([]string, 0)
	for id, count := range degree {
		if count == 0 {
			ready = append(ready, id)
		}
	}
	sort.Strings(ready)
	ordered := make([]RuleOutput, 0, len(outputs))
	for len(ready) > 0 {
		id := ready[0]
		ready = ready[1:]
		ordered = append(ordered, byID[id])
		for _, child := range children[id] {
			degree[child]--
			if degree[child] == 0 {
				ready = append(ready, child)
			}
		}
		sort.Strings(ready)
	}
	if len(ordered) != len(outputs) {
		return nil, fmt.Errorf("body poset contains a causal cycle")
	}
	return ordered, nil
}
